name: Manual
on:
  workflow_dispath:
    inputs:
      greeting:
        type: string
        default: Hello
        require: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
